### ISSUE TITLE
Custom validator

### ISSUE THREAD

**Issue by robert-waggott** [AjDrummer93/jquery.isValid#1]
Great plugin!

Any chance of a custom validator, one where I can pass in my own validation function? This would be awesome.

**Comment by ajsummerfield** [comment]
Have been working on this over the weekend and have now got this implemented and working. Will be updating documentation over the course of the week and then will push the changes onto master!

**Comment by ajsummerfield** [comment]
Hi @robert-waggott 

This is now done and you can download and do this!

Andy
